version: '2'
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    ports:
      - 9115:9115
    volumes:
      - ${PWD}/blackbox_exporter/blackbox_exporter.yml:/etc/blackbox_exporter/config.yml
